env:
  - DB=postgres
  - SH=bash
  - PACKAGE_VERSION="1.0.*"

language: node_js
node_js:
  - 12

script:
  - yarn test
  
after_success:
  - chmod +x .travis/build.sh
  - "./.travis/build.sh"

deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  application: "lucmurakami-website-backend"
  deployment_group: "lucmurakami-website-backend-deploygroup"
  region: "us-west-2"
  on:
    branch: production