sudo: 'required'

language: node_js
node_js:
  - 12

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - PATH=$HOME/.local/bin:$PATH

script:
  - yarn test
  - chmod +x .travis/build.sh
  - "./.travis/build.sh"
  
after_success:
  - bash .travis/update-service.sh

notifications:
  email: false
