sudo: 'required'

language: node_js
node_js:
  - 12

services:
  - docker

before_script:
  - yarn test

script:
  - chmod +x .travis/build.sh
  - "./.travis/build.sh"
  
# after_success:
#   - bash .travis/ecs-deploy.sh -c $ECS_CLUSTER -n $ECS_SERVICE -i ECR_BASE_URI/$ECR_REPO_NAME:latest

notifications:
  email: false
