sudo: 'required'

language: node_js
node_js:
  - 12

services:
  - docker

# install:
#   - pip install -U pip
#   - pip install awscli

# after_install:
#   - PATH=$HOME/.local/bin:$PATH

before_script:
  - yarn test

script:
  - chmod +x .travis/build.sh
  - "./.travis/build.sh"
  
# after_success:
#   - bash .travis/ecs-deploy.sh -c $ECS_CLUSTER -n $ECS_SERVICE -i $ECR_REPO_NAME

notifications:
  email: false
