sudo: 'required'

language: node_js
node_js:
  - 12

script:
  - yarn test
  - chmod +x .travis/build.sh
  - "./.travis/build.sh"
  
after_success:
  - chmod +x .travis/update-service.sh
  - chmod +x .travis/ecs-deploy.sh
  - bash .travis/update-service.sh

notifications:
  email: false
